name: Deploy to VPS

on:
    push:
        branches: ['master']

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Deploy using ssh
              uses: appleboy/ssh-action@v1.0.3
              with:
                  host: ${{ secrets.HOST }}
                  port: ${{ secrets.PORT }}
                  username: ${{ secrets.USERNAME }}
                  key: ${{ secrets.PRIVATE_KEY }}
                  script: |
                      cd ${{ secrets.SERVICES_PATH }}/SOK-api/
                      git pull origin master
                      cd ${{ secrets.SERVICES_PATH }}/
                      docker compose up -d --build ${{ secrets.CONTAINER_NAME }}
                      docker compose restart nginx
